name: Ruby

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        # Due to https://github.com/actions/runner/issues/849, we have to use quotes for '3.0'
        ruby: [2.3, 2.4, 2.6, 2.7, '3.0', 3.1]
        exclude:
          - os: windows-latest
            ruby: 2.3
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
      env:
        NTRIP_CASTER: "rtk2go.com:2101"
        NTRIP_AUTH: "test@example.com:none"
